parameters:
    snowio_connector.connector_name.csv: 'Snowio Connector'
    snowio_connector.job_name.snowio_complete_export: 'snowio_complete_export'

services:
    snowio_connector.job.snowio_complete_export:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%snowio_connector.job_name.snowio_complete_export%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@snowio_connector.step.csv_published_product.export'
                - '@snowio_connector.step.csv_product_model.export'
                - '@snowio_connector.step.csv_category.export'
                - '@snowio_connector.step.csv_attribute.export'
                - '@snowio_connector.step.csv_attribute_option.export'
                - '@snowio_connector.step.csv_family.export'
                - '@snowio_connector.step.csv_attribute_group.export'
                - '@snowio_connector.step.metadata'
                - '@snowio_connector.step.media_export'
                - '@snowio_connector.step.archive'
                - '@snowio_connector.step.post'
        tags:
            - { name: akeneo_batch.job, connector: '%snowio_connector.connector_name.csv%', type: '%pim_connector.job.export_type%' }
